name: false
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.2=0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - seaborn=0.11.0=py_0
  - pip:
    - numpy==1.20.2
    - pandas==1.2.4
    - sklearn==0.0
    - spacy==3.0.5
    - spacy-legacy==3.0.2
    - speechrecognition==3.8.1

