name: false
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.2=0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - seaborn=0.11.0=py_0
  - sklearn==0.0
  - numpy==1.20.2
  - pandas==1.2.4
  - sklearn==0.0
